name: TSB4_Daily_Test_Automation2_Flow

on:
  #schedule:
   # - cron: '5 9 * * *'
   # - cron: '20 2 * * *'
  workflow_dispatch: # 讓您可以手動點擊 Run workflow 測試

jobs:
  automation_process:
    runs-on: self-hosted # 指定在您的執行
    steps:
      - name: 1. 同步雲端腳本 (Checkout)
        uses: actions/checkout@v4
    
      - name: 2. 執行測試 FW upgrade and case1 Factory default Onboarding
        continue-on-error: true
        run: python run_all_cases_like_github.py --only initial_wait,fw_upgrade

      - name: 3. 執行測試 Case1
        continue-on-error: true
        run: python run_all_cases_like_github.py --only case1
        
      - name: 4. 執行測試 Case2, Case3, Case4
        continue-on-error: true
        run: python run_all_cases_like_github.py --only case2,case3,case4

      - name: 5. 執行測試 Case5, Case6
        continue-on-error: true
        run: python run_all_cases_like_github.py --only case5,case6

      - name: 6. 執行測試 Case7
        continue-on-error: true
        run: python run_all_cases_like_github.py --only case7

      - name: 7. 執行測試 Case8
        continue-on-error: true
        run: python run_all_cases_like_github.py --only case8

      - name: 8. 執行測試 Case9
        continue-on-error: true
        run: python run_all_cases_like_github.py --only case9

      - name: 9. 執行測試 Case10, Case11, Case13
        continue-on-error: true
        run: python run_all_cases_like_github.py --only case10,case13

      - name: 10. Collect All log 
        if: always()
        run: python run_all_cases_like_github.py --only collect

      - name: 11. Final TSM4 GUI Factory Default
        if: always()
        run: python tsm4_gui_factory_default_standalone.py

