name: TSB4_Test_Automation2_Flow

on:
  #schedule:
   # - cron: '5 9 * * *'
   # - cron: '55 6 * * *'
  workflow_dispatch: # 讓您可以手動點擊 Run workflow 測試

jobs:
  automation_process:
    runs-on: self-hosted # 指定在您的執行
    steps:
      - name: 1. 同步雲端腳本 (Checkout)
        uses: actions/checkout@v4

      - name: 等待 10 秒 
        run: Start-Sleep -s 10

      - name: 8.1. 執行測試 Case14
        continue-on-error: true
        run: python run_all_cases_like_github.py --only case14
        
      - name: 9. 執行測試 Case10, Case13
        continue-on-error: true
        run: python run_all_cases_like_github.py --only case10,case13

      - name: 10. Collect All log 
        if: always()
        run: python run_all_cases_like_github.py --only collect

      - name: 11. Final TSM4 GUI Factory Default
        if: always()
        run: python tsm4_gui_factory_default_standalone.py

