name: TSB4_Test_Automation2_Flow

on:
  #schedule:
   # - cron: '5 9 * * *'
   # - cron: '55 6 * * *'
  workflow_dispatch: # 讓您可以手動點擊 Run workflow 測試

jobs:
  automation_process:
    runs-on: self-hosted # 指定在您的執行
    steps:
      - name: 1. 同步雲端腳本 (Checkout)
        uses: actions/checkout@v4

      - name: 等待 10 秒 
        run: Start-Sleep -s 10

      - name: 8.1. 執行測試 Case2
        continue-on-error: true
        run: python run_all_cases_like_github.py --only case2
        


